// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/bloxapp/ssv/network/network_msgs.proto

package network

import (
	fmt "fmt"
	proto1 "github.com/bloxapp/ssv/ibft/proto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NetworkMsg int32

const (
	NetworkMsg_IBFTType      NetworkMsg = 0
	NetworkMsg_DecidedType   NetworkMsg = 1
	NetworkMsg_SignatureType NetworkMsg = 2
)

var NetworkMsg_name = map[int32]string{
	0: "IBFTType",
	1: "DecidedType",
	2: "SignatureType",
}

var NetworkMsg_value = map[string]int32{
	"IBFTType":      0,
	"DecidedType":   1,
	"SignatureType": 2,
}

func (x NetworkMsg) String() string {
	return proto.EnumName(NetworkMsg_name, int32(x))
}

func (NetworkMsg) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3bcf522045b4e980, []int{0}
}

type SyncMessage struct {
	T                    []byte   `protobuf:"bytes,1,opt,name=t,proto3" json:"t,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncMessage) Reset()         { *m = SyncMessage{} }
func (m *SyncMessage) String() string { return proto.CompactTextString(m) }
func (*SyncMessage) ProtoMessage()    {}
func (*SyncMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bcf522045b4e980, []int{0}
}

func (m *SyncMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncMessage.Unmarshal(m, b)
}
func (m *SyncMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncMessage.Marshal(b, m, deterministic)
}
func (m *SyncMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncMessage.Merge(m, src)
}
func (m *SyncMessage) XXX_Size() int {
	return xxx_messageInfo_SyncMessage.Size(m)
}
func (m *SyncMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SyncMessage proto.InternalMessageInfo

func (m *SyncMessage) GetT() []byte {
	if m != nil {
		return m.T
	}
	return nil
}

type Message struct {
	Lambda               []byte                `protobuf:"bytes,1,opt,name=Lambda,proto3" json:"Lambda,omitempty"`
	SignedMessage        *proto1.SignedMessage `protobuf:"bytes,2,opt,name=SignedMessage,proto3" json:"SignedMessage,omitempty"`
	Type                 NetworkMsg            `protobuf:"varint,3,opt,name=Type,proto3,enum=network.NetworkMsg" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bcf522045b4e980, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetLambda() []byte {
	if m != nil {
		return m.Lambda
	}
	return nil
}

func (m *Message) GetSignedMessage() *proto1.SignedMessage {
	if m != nil {
		return m.SignedMessage
	}
	return nil
}

func (m *Message) GetType() NetworkMsg {
	if m != nil {
		return m.Type
	}
	return NetworkMsg_IBFTType
}

func init() {
	proto.RegisterEnum("network.NetworkMsg", NetworkMsg_name, NetworkMsg_value)
	proto.RegisterType((*SyncMessage)(nil), "network.SyncMessage")
	proto.RegisterType((*Message)(nil), "network.Message")
}

func init() {
	proto.RegisterFile("github.com/bloxapp/ssv/network/network_msgs.proto", fileDescriptor_3bcf522045b4e980)
}

var fileDescriptor_3bcf522045b4e980 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4c, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0xca, 0xc9, 0xaf, 0x48, 0x2c, 0x28, 0xd0, 0x2f,
	0x2e, 0x2e, 0xd3, 0xcf, 0x4b, 0x2d, 0x29, 0xcf, 0x2f, 0xca, 0x86, 0xd1, 0xf1, 0xb9, 0xc5, 0xe9,
	0xc5, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0x31, 0x29, 0x2e, 0x84, 0xa0, 0x92,
	0x34, 0x17, 0x77, 0x70, 0x65, 0x5e, 0xb2, 0x6f, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0xaa, 0x10, 0x0f,
	0x17, 0x63, 0x89, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x63, 0x89, 0x52, 0x1b, 0x23, 0x17,
	0x3b, 0x4c, 0x46, 0x8c, 0x8b, 0xcd, 0x27, 0x31, 0x37, 0x29, 0x25, 0x11, 0x2a, 0x0d, 0xe5, 0x09,
	0x59, 0x71, 0xf1, 0x06, 0x67, 0xa6, 0xe7, 0xa5, 0xa6, 0x40, 0x15, 0x4a, 0x30, 0x29, 0x30, 0x6a,
	0x70, 0x1b, 0x89, 0x40, 0xcc, 0xd7, 0x43, 0x91, 0x0b, 0x42, 0x55, 0x2a, 0xa4, 0xce, 0xc5, 0x12,
	0x52, 0x59, 0x90, 0x2a, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x67, 0x24, 0xac, 0x07, 0x75, 0xa0, 0x9e,
	0x1f, 0x84, 0xf6, 0x2d, 0x4e, 0x0f, 0x02, 0x2b, 0xd0, 0xb2, 0xe3, 0xe2, 0x42, 0x88, 0x09, 0xf1,
	0x70, 0x71, 0x78, 0x3a, 0xb9, 0x85, 0x80, 0x64, 0x04, 0x18, 0x84, 0xf8, 0xb9, 0xb8, 0x5d, 0x52,
	0x93, 0x33, 0x53, 0x52, 0x53, 0xc0, 0x02, 0x8c, 0x42, 0x82, 0x10, 0x17, 0x25, 0x96, 0x94, 0x16,
	0xa5, 0x82, 0x85, 0x98, 0x9c, 0x14, 0xa2, 0xe4, 0xf0, 0x87, 0x57, 0x12, 0x1b, 0xd8, 0xb9, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x34, 0x75, 0x30, 0x58, 0x01, 0x00, 0x00,
}
